{{- if .Values.ingress.enabled }}
{{- $name := .Values.service.name }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $name }}-ingress
spec:
  entryPoints:
    - {{ .Values.ingress.entrypoint }}
  routes:
    - match: HostRegexp(`(?i)^([a-z0-9-]+\.)*{{ .Values.ingress.hosts.host }}$`) || Host(`{{ .Values.ingress.hosts.host }}`)
      kind: Rule
      middlewares: {{- range .Values.ingress.middlewares }}
        - name: {{ .name }}
          namespace: {{ .namespace }}
      {{- end }}
      services:
        - name: {{ $name }}
          port: {{ .Values.service.port }}
{{- end }}